// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5494.BizarBot2016;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSystemTankTopLeft;
    public static SpeedController driveSystemTankTopRight;
    public static SpeedController driveSystemTankBottomLeft;
    public static SpeedController driveSystemTankBottomRight;
    public static RobotDrive driveSystemTankRobotDrive41;
    public static SpeedController flippersFlipperLeft;
    public static SpeedController flippersFlipperRight;
    public static RobotDrive flippersRobotDrive21;
    public static SpeedController liftEndGameLift;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSystemTankTopLeft = new Talon(0);
        LiveWindow.addActuator("DriveSystemTank", "TopLeft", (Talon) driveSystemTankTopLeft);
        
        driveSystemTankTopRight = new Talon(1);
        LiveWindow.addActuator("DriveSystemTank", "TopRight", (Talon) driveSystemTankTopRight);
        
        driveSystemTankBottomLeft = new Talon(2);
        LiveWindow.addActuator("DriveSystemTank", "BottomLeft", (Talon) driveSystemTankBottomLeft);
        
        driveSystemTankBottomRight = new Talon(3);
        LiveWindow.addActuator("DriveSystemTank", "BottomRight", (Talon) driveSystemTankBottomRight);
        
        driveSystemTankRobotDrive41 = new RobotDrive(driveSystemTankTopLeft, driveSystemTankBottomLeft,
              driveSystemTankTopRight, driveSystemTankBottomRight);
        
        driveSystemTankRobotDrive41.setSafetyEnabled(true);
        driveSystemTankRobotDrive41.setExpiration(0.1);
        driveSystemTankRobotDrive41.setSensitivity(0.5);
        driveSystemTankRobotDrive41.setMaxOutput(1.0);

        flippersFlipperLeft = new Talon(4);
        LiveWindow.addActuator("Flippers", "FlipperLeft", (Talon) flippersFlipperLeft);
        
        flippersFlipperRight = new Talon(5);
        LiveWindow.addActuator("Flippers", "FlipperRight", (Talon) flippersFlipperRight);
        
        flippersRobotDrive21 = new RobotDrive(flippersFlipperLeft, flippersFlipperRight);
        
        flippersRobotDrive21.setSafetyEnabled(true);
        flippersRobotDrive21.setExpiration(0.1);
        flippersRobotDrive21.setSensitivity(0.5);
        flippersRobotDrive21.setMaxOutput(1.0);

        liftEndGameLift = new Talon(6);
        LiveWindow.addActuator("Lift", "EndGameLift", (Talon) liftEndGameLift);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
