// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5494.BizarBot2016;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSystemTopLeft;
    public static SpeedController driveSystemTopRight;
    public static SpeedController driveSystemBottomLeft;
    public static SpeedController driveSystemTankBottomRight;
    public static RobotDrive driveSystemRobotDrive41;
    public static SpeedController flippersFlipperLeft;
    public static SpeedController flippersFlipperRight;
    public static RobotDrive flippersRobotDrive21;
    public static SpeedController liftEndGameLift;
    public static Solenoid shooterSolenoid1;
    public static Solenoid shooterSolenoid2;
    public static Solenoid shooterSolenoid3;
    public static Solenoid shooterSolenoid4;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSystemTopLeft = new Talon(0);
        LiveWindow.addActuator("DriveSystemTank", "TopLeft", (Talon) driveSystemTopLeft);
        
        driveSystemTopRight = new Talon(1);
        LiveWindow.addActuator("DriveSystemTank", "TopRight", (Talon) driveSystemTopRight);
        
        driveSystemBottomLeft = new Talon(2);
        LiveWindow.addActuator("DriveSystemTank", "BottomLeft", (Talon) driveSystemBottomLeft);
        
        driveSystemTankBottomRight = new Talon(3);
        LiveWindow.addActuator("DriveSystemTank", "BottomRight", (Talon) driveSystemTankBottomRight);
        
        driveSystemRobotDrive41 = new RobotDrive(driveSystemTopLeft, driveSystemBottomLeft,
              driveSystemTopRight, driveSystemTankBottomRight);
        
        driveSystemRobotDrive41.setSafetyEnabled(true);
        driveSystemRobotDrive41.setExpiration(0.1);
        driveSystemRobotDrive41.setSensitivity(0.5);
        driveSystemRobotDrive41.setMaxOutput(1.0);

        flippersFlipperLeft = new Talon(4);
        LiveWindow.addActuator("Flippers", "FlipperLeft", (Talon) flippersFlipperLeft);
        
        flippersFlipperRight = new Talon(5);
        LiveWindow.addActuator("Flippers", "FlipperRight", (Talon) flippersFlipperRight);
        
        flippersRobotDrive21 = new RobotDrive(flippersFlipperLeft, flippersFlipperRight);
        
        flippersRobotDrive21.setSafetyEnabled(true);
        flippersRobotDrive21.setExpiration(0.1);
        flippersRobotDrive21.setSensitivity(0.5);
        flippersRobotDrive21.setMaxOutput(1.0);

        liftEndGameLift = new Talon(6);
        LiveWindow.addActuator("Lift", "EndGameLift", (Talon) liftEndGameLift);
        
        shooterSolenoid1 = new Solenoid(0, 0);
        shooterSolenoid2 = new Solenoid(0, 1);
        shooterSolenoid3 = new Solenoid(0, 2);
        shooterSolenoid4 = new Solenoid(0, 3);
        LiveWindow.addActuator("Solenoid", 4, shooterSolenoid1);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
