// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5494.BizarBot2016.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5494.BizarBot2016.Robot;
import org.usfirst.frc5494.BizarBot2016.RobotMap;

/**
 *
 */
public class CommandFlippers extends Command
{
	public CommandFlippers()
	{
		requires(Robot.flippers);
	}
	
	protected void initialize()
	{
	}
	
	protected void execute()
	{
		double Lt = Robot.oi.joystickOperator.getRawAxis(1); // left joystick  y //(2); // left trigger axis
		double Rt = Robot.oi.joystickOperator.getRawAxis(5); // right joystick y //(3); // right trigger axis
		
		RobotMap.flippersFlipperLeft.set((RobotMap.flippersLimitSwitchL.get() || Lt < 0) ? (Lt / 2) : 0);
		RobotMap.flippersFlipperRight.set((RobotMap.flippersLimitSwitchR.get() || -Rt < 0) ? (-Rt / 2) : 0);
	}
	
	protected boolean isFinished()
	{
		return false;
	}
	
	protected void end()
	{
	}
	
	protected void interrupted()
	{
	}
}
