// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5494.BizarBot2016.commands;

import org.usfirst.frc5494.BizarBot2016.Robot;
import org.usfirst.frc5494.BizarBot2016.RobotMap;

import edu.wpi.first.wpilibj.I2C;
import edu.wpi.first.wpilibj.I2C.Port;
import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class CommandDrive extends Command
{
	public CommandDrive() {
    	requires(Robot.driveSystem);
    	i2c = new I2C(Port.kOnboard, 0);
    }
    
    protected void initialize() {
    }
    
    I2C i2c;
    
    protected void execute() {
    	// made for XBox Controller
    	double LJy = -Robot.oi.joystickDriver.getRawAxis(1); // left joystick y axis
    	double LJx = -Robot.oi.joystickDriver.getRawAxis(0); // left joystick x axis
    	double RJy = -Robot.oi.joystickDriver.getRawAxis(5); // right joystick y axis
    	double RJx = -Robot.oi.joystickDriver.getRawAxis(4); // right joystick x axis
    	
    	// motor mapping for PWM cables
    	// 0 1
    	// 2 3
    	
    	// tank drive
    	//RobotMap.driveSystemRobotDrive41.tankDrive(LJy, RJy);
    	
    	// arcade drive
    	RobotMap.driveSystemRobotDrive41.arcadeDrive(-LJy, LJx);
    	
    	// misc controls
    	RobotMap.rawPWM9.set(RJy);
    	RobotMap.rawPWM6.set(RJx);
    	
    	// set display for voltage meter
    	i2c.broadcast(1, 14);
    	
    }
    
    protected boolean isFinished() {
        return false;
    }
    
    protected void end() {
    }
    
    protected void interrupted() {
    }
}
